language: c

os:
  - linux
  - osx

env:
  matrix:
    - DISTRO=fedora TAG=32 # the exclude is based on this one
    - DISTRO=ubuntu TAG=20.04

# https://docs.travis-ci.com/user/reference/osx/#macos-version
osx_image:
  # - xcode10.1 # latest 10.13
  # - xcode11.3 # latest 10.14
  - xcode11.6 # latest 10.15

script:
  - date
  - uname -a
  - echo $DISTRO $TAG
  - if [ $(uname) == "Darwin" ] ; then
    uname -a;
    cd scripts;
    sh 00_mac.sh -n;
    sh 05_python.sh;
    fi
  - if [ $(uname) == "Linux" ] ; then
    uname -a;
    docker build -f Dockerfile_${DISTRO} .;
    fi

jobs:
  exclude:
    # For each ENV in the matrix, except the first one add one exclude
    # job here:
    - os: osx
      ENV: DISTRO=ubuntu TAG=20.04
