language: c

os:
  - linux
  - osx

env:
  matrix:
    - FROM_DISTRO=fedora FROM_TAG=32 # the exclude is based on this one
    - FROM_DISTRO=fedora FROM_TAG=33
    - FROM_DISTRO=ubuntu FROM_TAG=20.04
    - FROM_DISTRO=ubuntu FROM_TAG=20.10

# https://docs.travis-ci.com/user/reference/osx/#macos-version
osx_image:
  - xcode10.1 # latest 10.13
  - xcode11.3 # latest 10.14
  - xcode11.6 # latest 10.15

script: ./build_$(uname).sh

jobs:
  allow_failures:
    - os: linux
      ENV: FROM_DISTRO=fedora FROM_TAG=33
  exclude:
    # For each ENV in the matrix, except the first one add one exclude
    # job here:
    - os: osx
      ENV: FROM_DISTRO=fedora FROM_TAG=33
    - os: osx
      ENV: FROM_DISTRO=ubuntu FROM_TAG=20.04
    - os: osx
      ENV: FROM_DISTRO=ubuntu FROM_TAG=20.10
