---
name: nodenv-opensuse-tumbleweed

on:
  push:
    paths:
      - 'share/nodenv/**'
      - make/apps/nodenv.mk
  workflow_run:
    workflows:
      - base-opensuse-tumbleweed
    types:
      - completed

jobs:
  app:
    uses: ./.github/workflows/common-app-cached.yml
    strategy:
      matrix:
        distro:
          - opensuse-tumbleweed
        application:
          - app-nodenv
        path_to_cache:
          - "~/.nodenv"
    with:
      distro: ${{ matrix.distro}}
      application: ${{ matrix.application }}
      path_to_cache: ${{ matrix.path_to_cache }}
