---
name: gh

on:
  push:
    paths:
      - make/apps/gh.mk
  workflow_run:
    workflows:
      - Docker images
    types:
      - completed

jobs:
  app:
    uses: ./.github/workflows/common-app.yml
    strategy:
      matrix:
        distro:
          - fedora-latest
          - ubuntu-rolling
          - ubuntu-devel
          - ubuntu-lts
          - ubuntu-22.04
          - opensuse-tumbleweed
        application:
          - app-gh
    with:
      distro: ${{ matrix.distro}}
      application: ${{ matrix.application }}
