---
name: pyenv-opensuse-tumbleweed

on:
  push:
    paths:
      - 'share/pyenv/**'
      - make/apps/pyenv.mk
  workflow_run:
    workflows:
      - base-opensuse-tumbleweed
    types:
      - completed

jobs:
  app:
    uses: ./.github/workflows/common-app-cached.yml
    strategy:
      matrix:
        distro:
          - opensuse-tumbleweed
        application:
          - app-pyenv
        path_to_cache:
          - "~/.pyenv"
    with:
      distro: ${{ matrix.distro}}
      application: ${{ matrix.application }}
      path_to_cache: ${{ matrix.path_to_cache }}
