---
name: nodenv-ubuntu

on:
  push:
    paths:
      - 'share/nodenv/**'
      - make/apps/nodenv.mk
      - Makefile
      - bootstrap.sh
  workflow_run:
    workflows:
      - base-ubuntu
    types:
      - completed

jobs:
  app:
    uses: ./.github/workflows/common-app-cached.yml
    strategy:
      matrix:
        distro:
          - ubuntu-rolling
          - ubuntu-devel
          - ubuntu-lts
          - ubuntu-22.04
        application:
          - nodenv
    with:
      distro: ${{ matrix.distro}}
      application: ${{ matrix.application }}
