---
name: nodenv-opensuse-tumbleweed

on:
  push:
    paths:
      - 'share/nodenv/**'
      - make/apps/nodenv.mk
  workflow_run:
    workflows:
      - base-opensuse-tumbleweed
    types:
      - completed

jobs:
  app:
    uses: ./.github/workflows/common-app-cached.yml
    strategy:
      matrix:
        distro:
          - fedora-latest
          - ubuntu-rolling
          - ubuntu-devel
          - ubuntu-lts
          - ubuntu-22.04
          - opensuse-tumbleweed
        application:
          - nodenv
    with:
      distro: ${{ matrix.distro}}
      application: ${{ matrix.application }}
