---
name: pyenv-opensuse-tumbleweed

on:
  push:
    paths:
      - 'share/pyenv/**'
      - make/apps/pyenv.mk
      - Makefile
      - bootstrap.sh
  workflow_run:
    workflows:
      - base-opensuse-tumbleweed
    types:
      - completed

jobs:
  app:
    uses: ./.github/workflows/common-app-cached.yml
    strategy:
      matrix:
        distro:
          - opensuse-tumbleweed
        application:
          - pyenv
    with:
      distro: ${{ matrix.distro}}
      application: ${{ matrix.application }}
