---
name: base-ubuntu

on:
  push:
    paths:
      - 'docker/ubuntu*/**'
      - 'make/base/**'
      - 'make/distro/**'
      - Makefile
      - bootstrap.sh

jobs:
  build-docker:
    uses: ./.github/workflows/common-docker.yml
    strategy:
      matrix:
        distro:
          - ubuntu-rolling
          - ubuntu-devel
          - ubuntu-lts
