---
name: Build and Install Matrix

on:
  push:
    # branches:
    #   - main
  pull_request:

jobs:
  build-and-install:
    runs-on: ubuntu-latest  # GitHub-hosted runner
    strategy:
      matrix:
        container:
          - ubuntu:22.04
          - fedora:41
    container:
      image: ${{ matrix.container }}  # Dynamically use the image from the matrix
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run make install
        env:
          DEBIAN_FRONTEND: noninteractive
          TZ: Etc/UTC
        run: |
          bash ./bootstrap.sh && make desktop

      - name: Run tests
        run: |
          # shellcheck disable=SC1090
          source ~/.bashrc && make test
