---
name: Build and Install Matrix

on:
  push:
    # branches:
    #   - main
  # pull_request:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ["ubuntu", "fedora"]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.distro }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache: true
          cache-repository: ghcr.io/${{ github.repository }}/cache
          file: docker/${{ matrix.distro }}/Dockerfile

  install-app:
    needs: build-docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - fedora
          - ubuntu
        application:
          - pyenv
          # - nodenv
    container:
      image: ghcr.io/${{ github.repository }}/${{ matrix.distro }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: make ${{ matrix.application }}

  # nodenv:
  #   needs: build-docker
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       distro:
  #         - fedora
  #   container:
  #     image: ghcr.io/${{ github.repository }}/${{ matrix.distro }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Run make
  #       env:
  #         DEBIAN_FRONTEND: noninteractive
  #         TZ: Etc/UTC
  #       run: make nodenv


  # app-1password:
  #   runs-on: ubuntu-latest  # GitHub-hosted runner
  #   # needs: [pyenv, nodenv]
  #   needs: build-docker
  #   strategy:
  #     matrix:
  #       container:
  #         # - ubuntu:24.04
  #         - ghcr.io/${{ github.repository }}/fedora:41
  #   container:
  #     image: ${{ matrix.container }}  # Dynamically use the image from the matrix
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Run make
  #       run: make app-1password

  # app-gh:
  #   runs-on: ubuntu-latest  # GitHub-hosted runner
  #   # needs: [pyenv, nodenv]
  #   needs: build-docker
  #   strategy:
  #     matrix:
  #       container:
  #         # - ubuntu:24.04
  #         - ghcr.io/${{ github.repository }}/fedora:41
  #   container:
  #     image: ${{ matrix.container }}  # Dynamically use the image from the matrix
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - run: make app-gh


  # app-tailscale:
  #   # this needs to run on plain images, because it requires a systemd integration
  #   runs-on: ubuntu-latest  # GitHub-hosted runner
  #   strategy:
  #     matrix:
  #       container:
  #         - ubuntu:24.04
  #         # - fedora:41  # fails on fedora
  #   container:
  #     image: ${{ matrix.container }}  # Dynamically use the image from the matrix
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - run: bash bootstrap.sh && make app-tailscale


  # app-resilio:
  #   runs-on: ubuntu-latest  # GitHub-hosted runner
  #   # needs: [pyenv, nodenv]
  #   needs: build-docker
  #   strategy:
  #     matrix:
  #       container:
  #         # - ubuntu:24.04
  #         - ghcr.io/${{ github.repository }}/fedora:41
  #   container:
  #     image: ${{ matrix.container }}  # Dynamically use the image from the matrix
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - run: make app-resilio


  # app-warp:
  #   runs-on: ubuntu-latest  # GitHub-hosted runner
  #   needs: [pyenv, nodenv]
  #   strategy:
  #     matrix:
  #       container:
  #         # - ubuntu:24.04
  #         - fedora:41
  #   container:
  #     image: ${{ matrix.container }}  # Dynamically use the image from the matrix
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Run make
  #       env:
  #         DEBIAN_FRONTEND: noninteractive
  #         TZ: Etc/UTC
  #       run: |
  #         bash ./bootstrap.sh && make app-warp




  #     # - name: Run tests
  #     #   run: |
  #     #     # shellcheck disable=SC1090
  #     #     source ~/.bashrc && make test
  #     #   shell: bash

  #     # - name: Install 1password
  #     #   run: |
  #     #     source ~/.bashrc && make 1password
  #     #   shell: bash

  #     # - name: Install resilio
  #     #   run: |
  #     #     source ~/.bashrc && make resilio
  #     #   shell: bash

  #     # - name: Install tailscale
  #     #   run: |
  #     #     source ~/.bashrc && make tailscale
  #     #   shell: bash
