---
name: Build and Install Matrix

on:
  push:
    # branches:
    #   - main
  # pull_request:

jobs:
  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ["ubuntu", "fedora"]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/metadata-action@v3
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: int128/kaniko-action@v1
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.distro }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache: true
          cache-repository: ghcr.io/${{ github.repository }}/cache
          file: docker/${{ matrix.distro }}/Dockerfile

  install-app:
    needs: build-docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - fedora
          - ubuntu
        application:
          - pyenv
          - nodenv
          - app-gh
          - app-1password
          - app-resilio
          - app-warp
    container:
      image: ghcr.io/${{ github.repository }}/${{ matrix.distro }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: make ${{ matrix.application }}

  app-tailscale:
    # this needs to run on plain images, because it requires a systemd integration
    runs-on: ubuntu-latest  # GitHub-hosted runner
    strategy:
      matrix:
        container:
          - ubuntu:24.04
          # - fedora:41  # fails on fedora
    container:
      image: ${{ matrix.container }}  # Dynamically use the image from the matrix
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: bash bootstrap.sh && make app-tailscale


