---
name: Deploy test

on:
  push:
    paths:
      - 'share/**'
      - 'make/**'
  workflow_run:
    workflows:
      - Docker images
    types:
      - completed

jobs:
  app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - fedora-latest
          - ubuntu-24.04
          - ubuntu-22.04
          - ubuntu-rolling
        application:
          - app-gh
          - app-ghq
          - app-1password
          - app-resilio
    container:
      image: ghcr.io/${{ github.repository }}/${{ matrix.distro }}
    steps:
      - uses: actions/checkout@v4
      - run: make ${{ matrix.application }}

  app-cached:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - fedora-latest
          - ubuntu-24-04
          - ubuntu-22.04
          - ubuntu-rolling
        application:
          - pyenv
          - nodenv
    container:
      image: ghcr.io/${{ github.repository }}/${{ matrix.distro }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "CACHE_PATH=share/${{ matrix.application }}/**" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          path: ~/.${{ matrix.application }}
          key: ${{ matrix.distro }}-${{ hashFiles(env.CACHE_PATH) }}
      - run: make ${{ matrix.application }}

  app-runner:
    # this needs to run on plain images, because it requires a systemd
    # integration
    runs-on: ubuntu-latest  # GitHub-hosted runner
    strategy:
      matrix:
        container: ["ubuntu:24.04"]
        app: ["app-tailscale", "app-warp"]
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
      - run: bash bootstrap.sh && make ${{ matrix.app }}
