---
name: Linux testing

on:
  push:
    paths:
      - 'share/nodenv/**'
      - 'share/pyenv/**'
      - 'make/**'
      - Makefile
      - bootstrap.sh
  workflow_run:
    workflows:
      - Docker images
    types:
      - completed

jobs:
  app:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      matrix:
        distro:
          - fedora-latest
          - ubuntu-rolling
          - ubuntu-devel
          - ubuntu-lts
          - ubuntu-22.04
        application:
          - app-gh
          - app-ghq
    container:
      image: ghcr.io/${{ github.repository }}/${{ matrix.distro }}
    steps:
      - uses: actions/checkout@v4
        with:
        # Use the triggering workflow's commit if available, otherwise default to the current branch
          ref: ${{ github.event.workflow_run.head_commit.id || github.ref_name }}
      - run: make ${{ matrix.application }}

  app-cached:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    strategy:
      matrix:
        distro:
          - fedora-latest
          - ubuntu-22.04
          - ubuntu-rolling
          - ubuntu-devel
          - ubuntu-lts
        application:
          - pyenv
          - nodenv
    container:
      image: ghcr.io/${{ github.repository }}/${{ matrix.distro }}
    steps:
      - uses: actions/checkout@v4
        with:
        # Use the triggering workflow's commit if available, otherwise default to the current branch
          ref: ${{ github.event.workflow_run.head_commit.id || github.ref_name }}
      - run: echo "CACHE_PATH=share/${{ matrix.application }}/**" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          path: ~/.${{ matrix.application }}
          key: ${{ matrix.distro }}-${{ hashFiles(env.CACHE_PATH) }}
      - run: make ${{ matrix.application }}

