---
name: Deploy test

on:
  push:
    paths:
      - 'share/**'
      - 'make/**'
      - Makefile
      - bootstrap.sh
  workflow_run:
    workflows:
      - Docker images
    types:
      - completed

jobs:
  app:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    strategy:
      matrix:
        distro:
          - fedora-latest
          - ubuntu-rolling
          - ubuntu-devel
          - ubuntu-lts
          - ubuntu-22.04
        application:
          - app-gh
          - app-ghq
          - app-1password
          - app-resilio
    container:
      image: ghcr.io/${{ github.repository }}/${{ matrix.distro }}
    steps:
      - uses: actions/checkout@v4
        with:
        # Use the triggering workflow's commit if available, otherwise default to the current branch
          ref: ${{ github.event.workflow_run.head_commit.id || github.ref_name }}
      - run: make ${{ matrix.application }}
      - run: make ${{ matrix.application }}-test

  app-cached:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    strategy:
      matrix:
        distro:
          - fedora-latest
          - ubuntu-22.04
          - ubuntu-rolling
          - ubuntu-devel
          - ubuntu-lts
        app:
          - pyenv
          - nodenv
    container:
      image: ghcr.io/${{ github.repository }}/${{ matrix.distro }}
    steps:
      - uses: actions/checkout@v4
        with:
        # Use the triggering workflow's commit if available, otherwise default to the current branch
          ref: ${{ github.event.workflow_run.head_commit.id || github.ref_name }}
      - run: echo "CACHE_PATH=share/${{ matrix.app }}/**" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          path: ~/.${{ matrix.app }}
          key: ${{ matrix.distro }}-${{ hashFiles(env.CACHE_PATH) }}
      - run: make ${{ matrix.app }}

  app-runner:
    # this needs to run on plain images, because it requires a systemd
    # integration
    runs-on: ubuntu-latest  # GitHub-hosted runner
    timeout-minutes: 3
    strategy:
      matrix:
        container: ["ubuntu:24.04"]
        app: ["app-tailscale", "app-warp"]
    container:
      image: ${{ matrix.container }}
    steps:
      - uses: actions/checkout@v4
        with:
        # Use the triggering workflow's commit if available, otherwise default to the current branch
          ref: ${{ github.event.workflow_run.head_commit.id || github.ref_name }}
      - run: bash bootstrap.sh && make ${{ matrix.app }}
      - run: make ${{ matrix.app }}-test
