---
name: Common docker images

on:
  workflow_call:
    inputs:
      distro:
        required: true
        type: string

jobs:
  build-docker:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: int128/kaniko-action@v1
        with:
          build-args: "BOOTSTRAP_BRANCH=${{ github.head_ref || github.ref_name }} "
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ inputs.distro }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache: true
          cache-repository: ghcr.io/${{ github.repository }}/cache
          file: docker/${{ inputs.distro }}/Dockerfile
