---
name: Docker images

on:
  push:
    paths:
      - 'docker/**'
      - 'make/base/**'
      - 'make/distro/**'
      - Makefile
      - bootstrap.sh

jobs:
  build-docker:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        distro: ["ubuntu-rolling", "fedora-latest", "ubuntu-devel", "ubuntu-lts"]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: int128/kaniko-action@v1
        with:
          build-args: "BOOTSTRAP_BRANCH=${{ github.head_ref || github.ref_name }} "
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.distro }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache: true
          cache-repository: ghcr.io/${{ github.repository }}/cache
          file: docker/${{ matrix.distro }}/Dockerfile
