---
name: FreeBSD testing

on:
  push:
    paths:
      - 'make/base/**'
      - 'make/server/**'
      - 'make/os/FreeBSD.mk'
      - Makefile

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to run test in FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v4
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: |
          pkg install -y bash

        run: |
          bash ./bootstrap.sh
          gmake base
          gmake server



