---
name: macOS

on:
  push:
    paths:
      - 'share/nodenv/**'
      - 'share/pyenv/**'
      - 'make/**'
      - Makefile
      - bootstrap.sh

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: |
          bash bootstrap.sh && make desktop
