---
name: macOS testing

on:
  push:
    paths:
      - 'share/**'
      - 'make/**'
      - Makefile
      - bootstrap.sh

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - run: |
          bash bootstrap.sh && make desktop
