---
name: openSUSE Tumbleweed 

on:
  push:
    # paths:
    #   - 'share/nodenv/**'
    #   - 'share/pyenv/**'
    #   - 'make/**'
    #   - Makefile
    #   - bootstrap.sh
  workflow_run:
    workflows:
      - Docker images
    types:
      - completed

jobs:
  app:
    uses: ./.github/workflows/linux-common.yml
    strategy:
      matrix:
        distro:
          - opensuse-tumbleweed
        application:
          - app-gh
          - app-ghq
    with:
      distro: ${{ matrix.distro}}
      application: ${{ matrix.application }}

  app-cached:
    uses: ./.github/workflows/linux-common.yml
    strategy:
      matrix:
        distro:
          - opensuse-tumbleweed
        application:
          - pyenv
          - nodenv
    with:
      distro: ${{ matrix.distro }}
      application: ${{ matrix.application}}
